name: typecast
description: >-
  Typecast allows you to convert one data type to another data type in Dart. Implicit conversions are allowed at compile time or runtime (VM), and explicit conversions can also be made in the source code.
version: 0.0.0
repository: https://github.com/odroe/dart-typecast

environment:
  sdk: '<4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
